corpus-callosum:
  container_name: corpus-callosum
  image: corpus-callosum:latest
  ports:
    - "5005:5000"
  volumes:
    - ".:/app"
  environment:
    - SERVICES_AUDITORY_CORTEX=
    - SERVICES_BROCAS_AREA=
    - SERVICES_CEREBRUM=
  links:
    - queue:queue

queue:
  container_name: corpus-callosum-queue
  image: redis:3.0-alpine
  ports:
    - "6000:6379"

worker:
  container_name: corpus-callosum-worker
  image: corpus-callosum:latest
  volumes:
    - ".:/app"
  environment:
    - SERVICES_AUDITORY_CORTEX=
    - SERVICES_BROCAS_AREA=
    - SERVICES_CEREBRUM=
  links:
    - queue:queue
  command: ["rq", "worker", "-c", "config.worker"] 
